### ISSUE TITLE
Sign Up not working

### ISSUE THREAD

**Issue by Nazi-pikachu** [codeakki/antdesign#54]
**Issue**
Sign up is not working.
**Steps to reproduce**

1.  start the backend server
2. start the frontend server
3. Try to create a user by signing up

**Expected Output**
User should be able to sign up and redirected to dashboard

**Actual Output**
![image](https://github.com/codeakki/YAUS-C4GT/assets/63303757/43843c8d-2b65-4c38-ab2b-e47b89b44555)

**Comment by Nazi-pikachu** [comment]
Hi @Kanika637 
I am working on migrating the codebase to the current monorepo of Yaus.  Since you have worked on this functionality can you give more info about the api endpoints being used to authenticate.
cc : @codeakki

**Comment by Spanda-User** [comment]
Hey @Nazi-pikachu, the APIs were given to me by my mentor when I was working on the authentication last year. If those don't work then kindly contact Chakshu Gautam Sir who is one of the mentors in C4GT.

**Comment by Kanika637** [comment]
Hey @Nazi-pikachu, the APIs were given to me by my mentor when I was working on the authentication last year. If those don't work then kindly contact Chakshu Gautam Sir who is one of the mentors in C4GT.

**Comment by Nazi-pikachu** [comment]
Thanks @Kanika637 will contach him for the same
